import 'package:flutter/material.dart';

abstract class AppStrings {
  static String welcomeTextTitle = 'Welcome to our';
  static String welcomeTextSubTitle = 'Social media app enjoy to connect world';
  static String aboutApp =
      'Step into a new world of connection! Discover, share, and connect with new friends and family in innovative and secure ways. Try our app today and make every moment you connect special!';
  static String getStart = 'Get Start';
  static String social = 'Social.';
  static String app = 'app';
  static List<String> singin_upList = ['Sing in', 'Sing Up'];
  static String email = 'Mail';
  static String invaledEmail = 'Invaled email';
  static String password = 'Password';
  static String forgetPass = 'Forget Password';
  static String validatepass = 'password can`t be less than 8 letters';
  static String validateemail = 'this feild is require';
  static String lohin = 'Login';
  static String singUp = 'SingUp';
  static String fristName = 'FristName';
  static String lastName = 'LastName';
  static String rePassword = 'Re-Password';
  static String passnotMatch = 'Password does not match';
  static String loading = 'loading...';
  static String successlogin = 'Success Login';
  static String getCode = 'Get Code';
  static String Code = 'Code';
  static String invalidCode = '    Invalid Code';
  static String validatecode = '    code can`t be less than 6 letters';
  static String Something = 'Something went wrong please try again later';
  static String socialApp = 'Social.app';
  static String noData = 'No Data to display';
  static String search = 'search';
  static List<String> tabBartext = ['Home', 'New Post', 'Chat', 'Profile'];
  static String mind = 'what`s in your mind';
  static String share = 'Share';
  static String sharingPost = 'Sharing your post';
  static String postAdded = 'your post added successfully';
  static String chooseSource = 'Schoose Image Source';
  static String fromCamera = 'Take a photo';
  static String fromGallery = 'Get image from gallery';
  static String updatingPic = 'Updating Profile picture';
  static String updatingCover = 'Updating Profile Cover';
  static String writeComment = 'Write a comment...';
  static String cansel = 'Cansel';
  static String delete = 'Delete';
  static String noComments = 'No Comments yet';
  static List<String> options = ['Edit', 'Delete'];
  static String update = 'Update';
  static String myStory = 'My Story';
  static String deletestory = 'Delete Story';
  static String repost = 'Repost';
}
